### ISSUE TITLE
Testing aioli; module cannot be found. 

### ISSUE THREAD

**Issue by happykhan** [biowasm/aioli#33]
I was writing some tests (RTL-JEST) for some components that imported Aioli. 

Jest kept throwing errors that it could not find `biowasm/aioli/aioli.js`

When I looked at the package.json for biowasm/aioli `main` seems to be pointing aioli.js in the root directory.  When I redirected it to the script in `dist/` it was fine. 

i.e. it is currently;

```
  "name": "@biowasm/aioli",
  "version": "2.4.0",
  "description": "A framework for building WebAssembly-based genomics tools",
  "browser": "dist/aioli.js",
  "worker": "dist/aioli.worker.js",
  main": "aioli.js",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/biowasm/aioli.git"
  },

```

I believe it should be: 

  **"main": "dist/aioli.js",**

**Comment by robertaboukhalil** [comment]
Nice catch, thanks @happykhan! Should be fixed now
