### ISSUE TITLE
how to add new tool to aioli?

### ISSUE THREAD

**Issue by orangeSi** [biowasm/aioli#40]
I had compile muscle v3 software to wasm by the guide at https://github.com/biowasm/biowasm/blob/main/CONTRIBUTING.md, but I do not know how to add this wasm to aioli? Could you give me some advice?

Thanks!
Si

**Comment by robertaboukhalil** [comment]
Hi @orangeSi,

To use it a WebAssembly binary you compiled locally, you can use these files:
* https://github.com/biowasm/aioli/blob/main/src/examples/test-biowasm.html
* https://github.com/biowasm/aioli/blob/main/src/examples/test-biowasm.js

In the .js file, you can set `urlPrefix` to the folder on your localhost server that contains the muscle .wasm and .js files. This is the localhost server you would have launched based on the instructions in [CONTRIBUTING.md](https://github.com/biowasm/biowasm/blob/main/CONTRIBUTING.md#development-setup)

Then you can open `localhost:PORT/test-biowasm.html` in your browser and it should run there!

**Comment by orangeSi** [comment]
my ```test-biowasm.js``` is :
```
const CLI = await new Aioli([
	{
		tool: "muscle",
		version: "3.8.1551",
		// URL at which .js/.wasm assets are located
		urlPrefix: "http://localhost:8000/",
	},
], { debug: true });


const version = await CLI.exec("muscle -version");
document.getElementById("output-version").innerHTML = version;
```
and my ```test-biowasm.html``` is:
```
<script src="https://biowasm.com/cdn/v3/aioli.js"></script>

<a href="test-biowasm.js">Code</a>

<h4>muscle version=</h4>
<pre id="output-version"></pre>

<script type="module" src="test-biowasm.js"></script>

```
and ```muscle.js + muscle.wasm + test-biowasm.js + test-biowasm.html```  are  in same directory, then I open ```test-biowasm.html``` by Chrome and get those two errors in console:
```
[WebWorker] Setting up muscle (base = true)...
muscle.js:1 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'WorkerGlobalScope': Failed to parse URL from muscle.wasm
    at instantiateAsync (muscle.js:1:7194)
    at createWasm (muscle.js:1:8129)
    at muscle.js:1:68802
    at Object._setup (f29041e4-fc67-4ad6-b09d-bae2df23de1d:1:7513)
    at Object.init (f29041e4-fc67-4ad6-b09d-bae2df23de1d:1:4026)
    at i (f29041e4-fc67-4ad6-b09d-bae2df23de1d:1:1015)
instantiateAsync @ muscle.js:1
createWasm @ muscle.js:1
（匿名） @ muscle.js:1
_setup @ f29041e4-fc67-4ad6-b09d-bae2df23de1d:1
init @ f29041e4-fc67-4ad6-b09d-bae2df23de1d:1
i @ f29041e4-fc67-4ad6-b09d-bae2df23de1d:1
Promise.then（异步）
instantiateAsync @ muscle.js:1
createWasm @ muscle.js:1
（匿名） @ muscle.js:1
_setup @ f29041e4-fc67-4ad6-b09d-bae2df23de1d:1
init @ f29041e4-fc67-4ad6-b09d-bae2df23de1d:1
i @ f29041e4-fc67-4ad6-b09d-bae2df23de1d:1
aioli.js:2 Uncaught TypeError: Module is not a function
    at Object._setup (blob:http://localhost:8000/f29041e4-fc67-4ad6-b09d-bae2df23de1d:1:7576)
    at Object.init (blob:http://localhost:8000/f29041e4-fc67-4ad6-b09d-bae2df23de1d:1:4026)
    at i (blob:http://localhost:8000/f29041e4-fc67-4ad6-b09d-bae2df23de1d:1:1015)
```

What should I do for above error?

thanks~
Si

**Comment by orangeSi** [comment]
I  try ```fasttree``` by guide at https://github.com/biowasm/biowasm/blob/main/tools/fasttree/compile.sh and also got the same above error.

**Comment by orangeSi** [comment]
I had resolve it by the guide at ```https://github.com/biowasm/biowasm/blob/main/bin/compile.py```, thanks~

**Comment by orangeSi** [comment]
I have one more question: ```urlPrefix ``` need a http server, so no http server is possiable for load *.js and *.wasm by some other workaround ?

**Comment by robertaboukhalil** [comment]
That's right, you need a web server. If you just open the .html file in your browser (by going to file:///test-biowasm.html), I think it will give an error when trying to load the .wasm.

**Comment by orangeSi** [comment]
when I use the way to complie software ```t_coffee``` (https://tcoffee.org/Projects/tcoffee/index.html) to wasm and got ```t_coffee.wasm``` without error, but when run in Chrome get error:

```
[WebWorker] Executing t_coffee -seq=input.fa -reg    args=null
20b6be06-daba-47f1-bec0-8e1412abe74c:1 RuntimeError: unreachable
    at set_nproc(int) (t_coffee.wasm:0x1689fa)
    at t_coffee_dpa(int, char**) (t_coffee.wasm:0x4735be)
    at batch_main(int, char**) (t_coffee.wasm:0x4538ab)
    at main (t_coffee.wasm:0x44d553)
    at VM13 t_coffee.js:1581:22
    at Object.callMain (VM13 t_coffee.js:5618:15)
    at Object.exec (20b6be06-daba-47f1-bec0-8e1412abe74c:1:5793)
    at i (20b6be06-daba-47f1-bec0-8e1412abe74c:1:1015)
```
detail of ``` at set_nproc(int) (t_coffee.wasm:0x1689fa)``` is as below:
```
  (func $set_nproc(int) (;882;) (param $var0 i32) (result i32)
    (local $var1 i32)
    (local $var2 i32)
    (local $var3 i32)
    (local $var4 i32)
    (local $var5 i32)
    global.get $__stack_pointer
    local.set $var1
    i32.const 16
    local.set $var2
    local.get $var1
    local.get $var2
    i32.sub
    local.set $var3
    local.get $var3
    local.get $var0
    i32.store offset=12
    local.get $var3
    i32.load offset=12
    local.set $var4
    i32.const 0
    local.set $var5
    local.get $var5
    local.get $var4
    i32.store offset=696988
    unreachable
  )
```

Do you occur the silimar error as above? 

Thanks~
Si

**Comment by orangeSi** [comment]
```t_coffee.wasm``` and ```t_coffee.js``` is in [t_coffee.wasm.js.zip](https://github.com/biowasm/aioli/files/12840498/t_coffee.wasm.js.zip)

**Comment by robertaboukhalil** [comment]
Since this is a separate issue, I moved it to https://github.com/biowasm/biowasm/issues/79 and I'll close this one, thanks
